0.0_Filtrage_GC
HerySon/teaching_ml_2023 pull request #18
Opened 2023-04-06 14:30 UTC by guillaumechupe

2023-04-11 12:00 UTC, HerySon requested changes

2023-04-11 12:00 UTC, HerySon commented on #0.0_Filtrage_GuillaumeCHUPE.py
> +    for col in df.columns:
Je pense que tu pourrais simplifier grandement ton code en utilisant la [méthode select_dtypes](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.select_dtypes.html?highlight=select_dtypes#pandas.DataFrame.select_dtypes) de pandas

2023-04-11 12:01 UTC, HerySon commented
@guillaumechupe 

Peux tu passer en revue les commentaires pour changer le comportement de ta fonction ?

2023-04-11 17:29 UTC, guillaumechupe commented
Quand il s'agit d'améliorer du code et de corriger les valeurs de retour par défaut, même Batman ne laisse rien passer. Découvrez comment le Chevalier Noir utilise la méthode select_dtypes pour filtrer les colonnes et optimiser son code comme un véritable génie en informatique !

- J'ai amélioré le code en utilisant la redoutable méthode select_dtypes, pour filtrer les colonnes comme un véritable chevalier noir.
- La valeur de retour par défaut pour les tests booléens a été corrigée en prenant en compte les paramètres par défaut des arguments, comme un vrai justicier vigilant.

Je mérite maintenant tous les points !!!

2023-04-25 12:54 UTC, HerySon commented on #0.0_Filtrage_GuillaumeCHUPE.py
> +        for col in downcast_cols:
Il faut donwcaster en fonction du type de la variable et non pas tout le temps par défaut en `int`. Par exemple, ici tu risque de downcaster des `float` en `int`

2023-04-25 13:12 UTC, merged