1.1_EncoderValeursNonNumeriques_GuillaumeCHUPE
HerySon/teaching_ml_2023 pull request #24
Opened 2023-04-07 09:59 UTC by guillaumechupe

2023-04-11 19:52 UTC, HerySon requested changes

2023-04-11 19:52 UTC, HerySon commented on #1.1_EncoderValeursNonNumeriques_GuillaumeCHUPE.py
> +
Il manque les imports des fonctions que tu utilises dans tout tes scripts !!!

2023-04-11 19:52 UTC, HerySon commented on #1.1_EncoderValeursNonNumeriques_GuillaumeCHUPE.py
> +    return data
la variable `encoded_data` n'est plus utilisée, il faut que tu la supprimes pour économiser de la RAM (souviens toi le dataset est volumineux !)

2023-04-11 19:52 UTC, HerySon commented on #1.1_EncoderValeursNonNumeriques_GuillaumeCHUPE.py
> +    return data
la variable `encoded_data` n'est plus utilisée, il faut que tu la supprimes pour économiser de la RAM (souviens toi le dataset est volumineux !)

2023-04-11 19:52 UTC, HerySon commented on #1.1_EncoderValeursNonNumeriques_GuillaumeCHUPE.py
> +    encoded_data = pd.DataFrame(encoded_cols.toarray(), columns=encoder.get_feature_names(cols))
Il faudrait laisser la possibilité à l'utilisateur de renvoyer une `matrice creuse (sparse matrix)` comme c'est le cas par défaut avec OHE avec l'argument [`sparse_output`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html#sklearn-preprocessing-onehotencoder)

2023-04-11 19:52 UTC, HerySon commented on #1.1_EncoderValeursNonNumeriques_GuillaumeCHUPE.py
> +def encode_hash(data, cols, n_components):
Je pense que tu pourrais laisser la valeur par défaut de `n_components = 8` comme dans le module correspondant

2023-04-11 19:53 UTC, HerySon commented
@guillaumechupe 
Bon travail ! Dès que tu auras fait les corrections mineures, je valide la tâche

## ToDo
- [ ] Faire les corrections mineures

2023-04-12 18:00 UTC, guillaumechupe commented on #1.1_EncoderValeursNonNumeriques_GuillaumeCHUPE.py
> +
je sais j'ai fais la meme erreur !! je corrige ; )

2023-04-12 18:00 UTC, guillaumechupe commented on #1.1_EncoderValeursNonNumeriques_GuillaumeCHUPE.py
> +    return data
tout à fait daccord, Fait

2023-04-12 18:00 UTC, guillaumechupe commented on #1.1_EncoderValeursNonNumeriques_GuillaumeCHUPE.py
> +    return data
tout à fait daccord, Fait

2023-04-12 18:00 UTC, guillaumechupe commented on #1.1_EncoderValeursNonNumeriques_GuillaumeCHUPE.py
> +    encoded_data = pd.DataFrame(encoded_cols.toarray(), columns=encoder.get_feature_names(cols))
ok j'avais pas pensé, fait

2023-04-12 18:03 UTC, guillaumechupe commented
- J'ai ajouté l'argument sparse_output à la fonction encode_onehot pour permettre à l'utilisateur de choisir si une matrice creuse (csr_matrix) doit être renvoyée, comme c'est le cas par défaut avec OneHotEncoder de scikit-learn. 

- J'ai également ajouté l'argument n_components à la fonction encode_hash pour permettre à l'utilisateur de spécifier le nombre de dimensions dans l'encodage, avec une valeur par défaut de 8 pour correspondre au module original.

- J'ai supprimé la variable encoded_data inutilisée dans les fonctions encode_onehot et encode_hash afin d'économiser de la RAM.

2023-04-25 09:31 UTC, merged