fonction pour visualiser le taux de remplissage des variables + fonction pour nettoyer le dataset
HerySon/teaching_ml_2023 pull request #26
Opened 2023-04-08 08:07 UTC by keagnon

2023-04-11 20:37 UTC, HerySon requested changes

2023-04-11 20:37 UTC, HerySon commented on scripts/data_cleaning.py
> +df = pd.read_csv(r"C:/Users/Fnac\Desktop/Trello ML/teaching_ml_2023/en.openfoodfacts.org.products.csv", nrows = 10000, sep='\t', encoding='utf-8',low_memory=False)
pas la peine de faire figurer ici le chargement de tes données, ca ne sera pas utilisé par l'utilisateur dans cette fonction (surtout si tu mets l'adresse fixe du chemin du fichier sur ton ordinateur)

2023-04-11 20:37 UTC, HerySon commented on scripts/data_cleaning.py
> +    """
Peux tu écrires tout tes commentaires et docstring en anglais ?

2023-04-11 20:37 UTC, HerySon commented on scripts/data_cleaning.py
> +    Calcule le taux de nullité de chaque variable dans un DataFrame et retourne une liste des variables avec un taux de nullité supérieur ou égal à un seuil donné.
phrase trop longue, il faut la scinder

2023-04-11 20:37 UTC, HerySon commented on scripts/data_cleaning.py
> +    - high_null_rate : DataFrame, une liste des variables avec leur taux de nullité supérieur ou égal au seuil spécifié, triée par ordre décroissant de taux de nullité
phrase trop longue, il faut la scinder

2023-04-11 20:37 UTC, HerySon commented on scripts/data_cleaning.py
> +nettoyer_donnees(df)
Si tu cherches à appeler ta fonction à l'éxecution du script il aurrait fallu utiliser:
`if __name__ == __main__:
nettoyer_donnees(df)`

2023-04-11 20:37 UTC, HerySon commented on scripts/data_cleaning.py
> +    colonnes_val_manquantes = pourcentages_val_manquantes[pourcentages_val_manquantes > 40].index
Tu pourrais utiliser ta fonction `taux_remplissage_variables` pour faire cela. Dailleurs tu devrais harmoniser changer le taux de variable manquante (soit à 40%, soit à 50% mais garde la même valeur dans ton module)

2023-04-13 09:03 UTC, keagnon commented on scripts/data_cleaning.py
> +df = pd.read_csv(r"C:/Users/Fnac\Desktop/Trello ML/teaching_ml_2023/en.openfoodfacts.org.products.csv", nrows = 10000, sep='\t', encoding='utf-8',low_memory=False)
Mofication effectuée

2023-04-13 09:03 UTC, keagnon commented on scripts/data_cleaning.py
> +    """
Mofication effectuée

2023-04-13 09:03 UTC, keagnon commented on scripts/data_cleaning.py
> +    Calcule le taux de nullité de chaque variable dans un DataFrame et retourne une liste des variables avec un taux de nullité supérieur ou égal à un seuil donné.
Mofication effectuée

2023-04-13 09:12 UTC, keagnon commented
Mofication effectuée

2023-04-25 17:07 UTC, merged