1.0 thomas payan
HerySon/teaching_ml_2023 pull request #33
Opened 2023-04-11 15:38 UTC by Thomas23456

Preprocessing :

- Suppression des valeurs dupliquées
- Suppression des features en fonction d'un seuil de données manquantes
- Imputation des données manquantes : features numériques et catégorielles

2023-04-12 14:06 UTC, HerySon requested changes

2023-04-12 14:06 UTC, HerySon commented on scripts/Preprocessing.py
> +            self.df[col] = self.df[col].astype('category')
Remarque : c'est correct, mais au final ca revient à utiliser un `LabelEncoder` de scikit-learn. En théorie on préfére utiliser `OneHotEncoder` pour les features catégorielles

2023-04-12 20:18 UTC, Thomas23456 commented on scripts/Preprocessing.py
> +        calc_null = [(c, self.df[c].isna().mean()*100) for c in self.df]
Je calcule le pourcentage des valeurs nulles pour chacune des colonnes, le fonction "iterrows" permet d'itérer sur les lignes du Dataframe sachant qu'avec le morceau de code ci-dessous, je calcule la moyenne d'apparition de la valeur NULL pour chacune des colonnes que je multiplie ensuite par 100 pour l'avoir en pourcentage.
```py
(col, self.df[col].isna().mean()*100) for col in self.df
```
Le morceau de code ci-dessous donne le même résultat :
```py
calc_null = [(col, self.df[col].isna().sum()*100 / len(self.df[col])) for col in self.df]
```

2023-04-13 14:24 UTC, Thomas23456 commented on scripts/Preprocessing.py
> +            self.df[col] = self.df[col].astype('category')
Une partie des colonnes qui ne semblent pas pertinentes sont supprimées dans la tâche 0.0 que je dois terminer.

Concernant la gestion des features erronnées, je me suis focalisé sur les variables avec des données numériques terminant par "_100g". Les fonctions sont assez spécifiques mais traitent plus de la moitié des données du dataset.

Le traitement est le suivant :
- Vérification du min, max et mean de la fonction describe de chacune des features. Le but étant de sélectionner les features avec des valeurs dont : 0 <= min et max <= 100 et 0 <= mean <=100 (la moyenne permettant d'exclure les features dont l'unité pourrait ne pas être exprimée en % ou en g.
- Remplacement des valeurs qui ne respectent pas les conditions par 3 méthodes basiques possibles : mean/median/mode (méthode héritée du choix de l'utilisateur dans l'initialisation de l'objet)

2023-04-25 12:29 UTC, merged