Tache4.0 GC
HerySon/teaching_ml_2023 pull request #7
Opened 2023-04-06 06:55 UTC by guillaumechupe

2023-04-07 14:41 UTC, HerySon requested changes

2023-04-07 14:41 UTC, HerySon commented on 4.0_Visualisation_GuillaumeCHUPE/#4.0_visualisation_GC.py
> +#from wordcloud import WordCloud
Pourquoi avoir commenté le module WordCloud ? Il est appelé dans ta fonction

2023-04-07 14:41 UTC, HerySon commented on 4.0_Visualisation_GuillaumeCHUPE/#4.0_visualisation_GC.py
> +        # Test if the function ednsity runs without errors
correction de density

2023-04-07 14:41 UTC, HerySon commented on 4.0_Visualisation_GuillaumeCHUPE/#4.0_visualisation_GC.py
> +#from wordcloud import WordCloud
Idem pour pyplot et pandas

2023-04-07 14:41 UTC, HerySon commented on 4.0_Visualisation_GuillaumeCHUPE/#4.0_visualisation_GC.py
> +      def setUp(self):
Peux tu changer la méthode setUp, pour la passer en tant que constructeur de ta classe ? Afin qu'elle soit appellée automatiquement

2023-04-07 14:45 UTC, guillaumechupe commented on 4.0_Visualisation_GuillaumeCHUPE/#4.0_visualisation_GC.py
> +#from wordcloud import WordCloud
je pensais qu'il fallait les mettre dans requirements.txt

2023-04-07 14:46 UTC, HerySon commented on 4.0_Visualisation_GuillaumeCHUPE/#4.0_visualisation_GC.py
> +        plot_histogram(self.df, 'col4')
Peux tu ajouter un bout de code pour exécuter automatiquement ta classe:
if __name__ == "__main__":
    ....

2023-04-07 14:51 UTC, HerySon commented on 4.0_Visualisation_GuillaumeCHUPE/#4.0_visualisation_GC.py
> +    class TestVisualizationFunctions(unittest.TestCase):
Pas besoin d'utiliser le module unittest ici, car les tests à réaliser ne sont pas très pratiques pour des graphiques (voir [ce post](https://stackoverflow.com/questions/27948126/how-can-i-write-unit-tests-against-code-that-uses-matplotlib)) . Donc tu peux enlever l'héritage de la classe unittest dans ta classe

2023-04-07 14:55 UTC, HerySon commented
@guillaumechupe Bon travail :)

## Todo
- [ ] faire les corrections mineures citées plus haut
- [ ]  pour chaque fonction, préciser le type de colonne attendu pour chaque type de graphe (numérique, str, ...) et rajouter une condition pour vérifier que la variable traitée est du type attendu

2023-04-10 07:54 UTC, guillaumechupe commented on 4.0_Visualisation_GuillaumeCHUPE/#4.0_visualisation_GC.py
> +#from wordcloud import WordCloud
Daccord, c'est fait

2023-04-10 07:55 UTC, guillaumechupe commented on 4.0_Visualisation_GuillaumeCHUPE/#4.0_visualisation_GC.py
> +        # Test if the function ednsity runs without errors
fait

2023-04-10 07:55 UTC, guillaumechupe commented on 4.0_Visualisation_GuillaumeCHUPE/#4.0_visualisation_GC.py
> +      def setUp(self):
Fait

2023-04-10 07:55 UTC, guillaumechupe commented on 4.0_Visualisation_GuillaumeCHUPE/#4.0_visualisation_GC.py
> +        plot_histogram(self.df, 'col4')
Fait

2023-04-10 07:55 UTC, guillaumechupe commented on 4.0_Visualisation_GuillaumeCHUPE/#4.0_visualisation_GC.py
> +    class TestVisualizationFunctions(unittest.TestCase):
Fait

2023-04-10 08:06 UTC, guillaumechupe commented
- corrections mineurs faites 
- suppression de la tache 3.0 pas au bon endroit
- rajout dans les arguments du types de colonnes attendu
-  rajout d'une condition de verification du type de colonne

2023-04-25 09:58 UTC, HerySon approved these changes

2023-04-25 10:08 UTC, merged