4-3_Embeding_visualization_EGHIAZARIAN_Sacha
HerySon/teaching_ml_2023 pull request #72
Opened 2023-04-13 14:57 UTC by Yonuko

2023-04-19 16:31 UTC, HerySon requested changes

2023-04-19 16:31 UTC, HerySon commented on scripts/Embeding_visualizer.py
> +        """Convert text to embeding vector
```suggestion
        """Convert text to tokens
```

2023-04-19 16:31 UTC, HerySon commented on scripts/Embeding_visualizer.py
> +        self.model = Word2Vec(sentences=tokens, vector_size=100, window=5, min_count=1, workers=4)
il faudrait pouvoir laisser la possibilité à l'utilisateur de modifier les paramètres de Word2Vec dans ta fonction. Cela peut se faire à minima en y incluant un argument optionnel `**kwargs`

2023-04-19 16:31 UTC, HerySon commented on scripts/Embeding_visualizer.py
> +                    If True, return the most similar words
il manque la définition de l'argument `return_only_word`

2023-04-19 16:31 UTC, HerySon commented on scripts/Embeding_visualizer.py
> +            tokens.append(self.model.wv[word])
Ici encore le choix du nom token n'est pas le plus judicieux puisque tu y stocke les vecteurs de mots et non pas les tokens

2023-04-19 16:31 UTC, HerySon commented on scripts/Embeding_visualizer.py
> +        new_values = tsne_model.fit_transform(pd.DataFrame(tokens).values)
ca serait plus propre de consitituer ton data frame en concatnenant suivant l'axe des colonnes les vecteurs de mots de ta liste

2023-04-19 16:31 UTC, HerySon commented on scripts/Embeding_visualizer.py
> +            x.append(value[0])
La matrice renvoyée par le `fit_transform` de tSNE à pour dimension (n_samples, n_components). Ici tu récupéres les 1ère et deuxième obesrvations seulement, je ne suis pas sur que ce soit ce que tu veuilles représenter, mais plutot les vecteurs de composantes de toutes les observations.
Ne serait ce pas plutot :
```python 
x.append(value[:, 0])
y.append(value[:, 0])
```

2023-04-19 16:32 UTC, HerySon commented
@Yonuko 

Bon travail général accompagné d'un exemple sur une variable pertinente. Il reste des petites modifications à faire

## todo
- [ ] faire les corrections mineures

2023-04-19 16:35 UTC, Yonuko commented on scripts/Embeding_visualizer.py
> +        labels = []
Elle ne l'est pas effectivement, mauvais copié coller de mon code

2023-04-19 16:40 UTC, Yonuko commented on scripts/Embeding_visualizer.py
> +    def get_tsne_transform(self, datas : list, perplexity: float = 40, n_components: int = 2, init: str = "pca", n_iter: int = 2500):
Fait

2023-04-19 16:42 UTC, Yonuko commented on scripts/Embeding_visualizer.py
> +                    If True, return the most similar words
C'est ajouté

2023-04-19 16:43 UTC, Yonuko commented on scripts/Embeding_visualizer.py
> +        self.model = Word2Vec(sentences=tokens, vector_size=100, window=5, min_count=1, workers=4)
J'ai rajouté un **kwargs

2023-04-19 16:43 UTC, Yonuko commented on scripts/Embeding_visualizer.py
> +        """Convert text to embeding vector
C'est corrigé

2023-04-19 16:44 UTC, Yonuko commented on scripts/Embeding_visualizer.py
> +            x.append(value[0])
le value[:, 0] ne fonctionne pas, je vais regarder comment appliquer ce changement sans générer une erreur

2023-04-19 16:51 UTC, Yonuko commented on scripts/Embeding_visualizer.py
> +            x.append(value[0])
En relançant mon code je viens de voir en affichant `tsne_values[0]` je reçois `[-64.29302 -60.17395]` puisque mon tsne n'a que 2 composantes, ce bout de code récupère donc bien la valeur de x du mot (tsne_values[i][0]) et la valeur y (tsne_values[i][1])

2023-04-26 09:55 UTC, HerySon approved these changes

2023-04-26 09:55 UTC, merged