Grace tache 5.0
HerySon/teaching_ml_2023 pull request #87
Opened 2023-04-13 23:23 UTC by keagnon

L'objectif de cette tache est d'entraîner et optimiser les K-means sur l'ensemble de données.
Pour ce fait, j'ai défini une fonction train_and_optimize_kmeans qui contient plusieurs paramètres et retourne le nombre optimal de clusters, tel que déterminé par le score de silhouette.

2023-04-21 13:27 UTC, HerySon requested changes

2023-04-21 13:27 UTC, HerySon commented on scripts/kmeans.py
> +    import pandas as pd
Il vaut mieux placer les imports en début de fichier, pas dans la fonction

2023-04-21 13:27 UTC, HerySon commented on scripts/kmeans.py
> +        data(str): OpenFoodFacts dataset file.
A modifier : tu utilises data comme un dataframe dans la suite du code

2023-04-21 13:27 UTC, HerySon commented on scripts/kmeans.py
> +    # Apply dimensionality reduction if needed
Rendre l'utilisation de la PCA optionnelle via un argument

2023-04-21 13:27 UTC, HerySon commented on scripts/kmeans.py
> +    scaler = StandardScaler()
Meme remarque

2023-04-21 13:27 UTC, HerySon commented on scripts/kmeans.py
> +    kmeans = KMeans(n_clusters=num_clusters, random_state=42)
Laisser la possibilité à l'utilisateur de changer les hyperparametres de KMeans. Par exemple en passant à ta fonction l'argument optionnel `**kwargs`

2023-04-21 13:28 UTC, HerySon commented
@keagnon 

## todo
- [ ] faire le changements mineurs

2023-04-24 08:59 UTC, keagnon commented on scripts/kmeans.py
> +    import pandas as pd
Modification effectuée

2023-04-24 08:59 UTC, keagnon commented on scripts/kmeans.py
> +        data(str): OpenFoodFacts dataset file.
Modification effectuée

2023-04-24 10:14 UTC, keagnon commented on scripts/kmeans.py
> +    scaler = StandardScaler()
Modification effectuée

2023-04-24 10:15 UTC, keagnon commented on scripts/kmeans.py
> +    kmeans = KMeans(n_clusters=num_clusters, random_state=42)
Modification effectuée

2023-04-24 10:25 UTC, keagnon commented
Comme demandé, j'ai effectué les modifications que vous m'avez demandées et le code est plus précis, offrant la possibilité à l'utilisateur d'utiliser le PCA, de choisir les hyperparamètres adaptés à ses besoins et de réaliser un scaling ou non.

2023-04-25 14:30 UTC, HerySon approved these changes

2023-04-25 14:34 UTC, merged