Grace tache 5.1
HerySon/teaching_ml_2023 pull request #88
Opened 2023-04-13 23:38 UTC by keagnon

Implémenter et optimiser un autre algorithme de clustering (que K-Means) : 
création d'une fonction train_and_optimize_DBSCAN

2023-04-21 13:58 UTC, HerySon requested changes

2023-04-21 13:58 UTC, HerySon commented on scripts/train_and_optimize_DBSCAN.py
> +def train_and_optimize_DBSCAN(data, feature_cols, eps_min=0.1, eps_max=1.0, eps_step=0.1, min_samples_min=2, min_samples_max=10, min_samples_step=1):
ligne trop longue, à scinder !

2023-04-21 13:58 UTC, HerySon commented on scripts/train_and_optimize_DBSCAN.py
> +    # Normalize the data
Rendre le scaling optionnel en introduisant un argument dédié

2023-04-21 13:58 UTC, HerySon commented on scripts/train_and_optimize_DBSCAN.py
> +    for eps in np.arange(eps_min, eps_max + eps_step, eps_step):
Cette optimisation manuelle du paramètre `eps` est intéressante mais tu aurais pu tout simplement faire un GridSearch à la place, cela aurait fonctionné suivant le même principe mais tu aurais pu tester également d'autres paramètres en même temps, par exemple, `min_samples`

2023-04-21 13:58 UTC, HerySon commented on scripts/train_and_optimize_DBSCAN.py
> +    data = pd.DataFrame({
Cela aurait été plus intéressant de le tester avec un échantillon du data set réel

2023-04-21 13:59 UTC, HerySon commented
@keagnon 

## todo
- [ ] faire les corrections mineures

2023-04-24 10:29 UTC, keagnon commented on scripts/train_and_optimize_DBSCAN.py
> +def train_and_optimize_DBSCAN(data, feature_cols, eps_min=0.1, eps_max=1.0, eps_step=0.1, min_samples_min=2, min_samples_max=10, min_samples_step=1):
Modification effectuée

2023-04-24 10:44 UTC, keagnon commented on scripts/train_and_optimize_DBSCAN.py
> +    # Normalize the data
oui c'est fait, modificaton effectuée

2023-04-24 10:44 UTC, keagnon commented on scripts/train_and_optimize_DBSCAN.py
> +    for eps in np.arange(eps_min, eps_max + eps_step, eps_step):
oui c'est fait, modificaton effectuée

2023-04-24 10:44 UTC, keagnon commented on scripts/train_and_optimize_DBSCAN.py
> +    data = pd.DataFrame({
oui c'est fait, modificaton effectuée

2023-04-24 10:46 UTC, keagnon commented
Modification effectuée

2023-04-25 15:05 UTC, merged